version: '3.8'
services:
    app:
        container_name: challenge-poke-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI=mongodb://mongo:27017/pokemon
        depends_on:
            - mongo
        volumes:
            - .:/app
            - /app/node_modules

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
